from __future__ import annotations

from enum import Enum


class ApplicabilityReason(str, Enum):
    APPLICABLE_CONTEXT_VALID = "APPLICABLE_CONTEXT_VALID"
    APPLICABLE_INPUTS_VALID = "APPLICABLE_INPUTS_VALID"
    REQUIRED_PHYSICAL_ENTITY_MISSING = "REQUIRED_PHYSICAL_ENTITY_MISSING"
    INVALID_ENTITY_TYPE = "INVALID_ENTITY_TYPE"
    CONTEXT_MISSING = "CONTEXT_MISSING"
    CONTEXT_INCOMPLETE = "CONTEXT_INCOMPLETE"
    REQUIRED_INPUT_MISSING = "REQUIRED_INPUT_MISSING"
    INPUT_VALUE_INVALID = "INPUT_VALUE_INVALID"
    INPUT_UNIT_MISSING = "INPUT_UNIT_MISSING"
    INPUT_UNIT_INCOMPATIBLE = "INPUT_UNIT_INCOMPATIBLE"
    INPUT_OUT_OF_DOMAIN = "INPUT_OUT_OF_DOMAIN"
    MODEL_NOT_REGISTERED = "MODEL_NOT_REGISTERED"
    MODEL_NOT_AVAILABLE = "MODEL_NOT_AVAILABLE"
    MODEL_INACTIVE = "MODEL_INACTIVE"
    MODEL_BENCHED = "MODEL_BENCHED"
    MODEL_RETIRED = "MODEL_RETIRED"
    MODEL_INVALID = "MODEL_INVALID"
    MODEL_SUPERSEDED = "MODEL_SUPERSEDED"
    MODEL_VERSION_UNAVAILABLE = "MODEL_VERSION_UNAVAILABLE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    EVIDENCE_INVALID = "EVIDENCE_INVALID"
    EVIDENCE_OUTDATED = "EVIDENCE_OUTDATED"
    CONTRACT_VIOLATION = "CONTRACT_VIOLATION"
    APPLICABILITY_UNDETERMINED = "APPLICABILITY_UNDETERMINED"
